INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Amy', 'Boyd', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Ana', 'Demeny', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Annie', 'Talvasto', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Alan', 'Smith', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Barbara', 'Forbes', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Denned', 'Torres', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Emma', 'D’Arcy', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Erik', 'Lieben', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Erwin', 'Staal', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Esther', 'Barthel', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Eve', 'Pardi', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Freek', 'Berson', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Geert', 'van der Cruijsen', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Heini', 'Ilmarinen', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Henk', 'Boelman', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Holly', 'Lehman', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Isodora', 'Katanic', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Karel', 'De Winter', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Karl', 'Ots', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Maik', 'van der Gaag', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Mark', 'Hayes', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Sandro', 'Pereira', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Stacy', 'Cashmore', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Stefano', 'Mostarda', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Tiago', 'Costa', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Tom', 'Kerkhove', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Vladimir', 'Stefanovic', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Will', 'Velida', 1)
INSERT INTO dbo.Person(Name, Surname, CountryId) VALUES ('Wim', 'Matthyssen', 1)
